@extends('layouts.app')

@section('content')
    <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div class="min-w-0">
            <h1 class="text-2xl font-semibold tracking-tight">Audit Trail</h1>
            <div class="text-sm text-slate-500">Live system audit logs generated by admin actions.</div>
        </div>

        <div class="flex flex-col sm:flex-row gap-2 sm:items-center">
            <x-search-input placeholder="Search logs..." />
            <a href="{{ route('admin.audit.exportCsv') }}" class="h-10 px-4 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-medium inline-flex items-center">Export CSV</a>
        </div>
    </div>

    <div class="mt-6 bg-white border border-slate-200/80 rounded-2xl p-5">
        <div class="flex items-center justify-between gap-3">
            <div class="text-sm font-semibold">Latest Events</div>
            <div class="text-sm text-slate-500">Latest 150</div>
        </div>

        <div class="mt-4 overflow-x-auto rounded-2xl border border-slate-200/80">
            <table class="min-w-[1100px] w-full text-sm">
                <thead class="bg-slate-50">
                    <tr>
                        <th class="text-left px-4 py-3 font-semibold text-slate-600">Time</th>
                        <th class="text-left px-4 py-3 font-semibold text-slate-600">Action</th>
                        <th class="text-left px-4 py-3 font-semibold text-slate-600 hidden md:table-cell">Target</th>
                        <th class="text-left px-4 py-3 font-semibold text-slate-600">Result</th>
                        <th class="text-left px-4 py-3 font-semibold text-slate-600 hidden lg:table-cell">IP</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse (($auditLogs ?? []) as $log)
                        <tr class="border-t border-slate-200/80">
                            <td class="px-4 py-3 text-slate-600">{{ $log->occurred_at?->format('Y-m-d H:i:s') ?? '—' }}</td>
                            <td class="px-4 py-3 font-medium">{{ $log->action }}</td>
                            <td class="px-4 py-3 text-slate-600 hidden md:table-cell">
                                @if ($log->target_type)
                                    {{ $log->target_type }} #{{ $log->target_id ?? '—' }}
                                @else
                                    —
                                @endif
                            </td>
                            <td class="px-4 py-3">
                                @if (($log->result ?? 'ok') === 'ok')
                                    <x-status-badge variant="stable">OK</x-status-badge>
                                @else
                                    <x-status-badge variant="critical">{{ $log->result }}</x-status-badge>
                                @endif
                            </td>
                            <td class="px-4 py-3 text-slate-600 hidden lg:table-cell">{{ $log->ip ?? '—' }}</td>
                        </tr>
                    @empty
                        <tr class="border-t border-slate-200/80">
                            <td class="px-4 py-6 text-slate-500" colspan="5">No audit logs yet.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection
